### Seqeunce Types - Stings, Lists and Tuples

### a) Theory for Strings:

In [ ]:
Properties of strings:
    
1) Immutable
2) Ordered & Indexed
3) Iterable
4) Supports slicing, concatenation, repetition
5) Case-sensitive
6) Works with membership operators
7) Strings are defined in single '' or double Quotes ""

### Programs on Strings

In [ ]:
1. Explain string slicing with examples

In [20]:
text = "Programming"
print(text[0:6])   # Progra
print(text[:6])     # Progra
print(text[3:])    # gramming
print(text[3:11])   # gramming
print(text[-3:-6:-1]) # Reverse printing
print(text[-8:-4])  # negative indexing
print(text[::-1])  # Reverse the entire string

Progra
Progra
gramming
gramming
imm
gram
gnimmargorP


In [ ]:
2a) Program to split the sentence into list of words 
b) Join the list of words with '-'
c) Replace '-' with space

** Demonstrate split(), join(), and replace() String methods.
** Explain any three methods of strings with examples.

In [8]:
s = "This is a sample string with sample words."
w = s.split()
print("Spliting result:", w)

p = "-".join(w)
print("Joining result:" , p)

r = p.replace('-', " ")  
print("Replacing result:", r)

# new_text =/text)   # replaces all spaces with -

Spliting result: ['This', 'is', 'a', 'sample', 'string', 'with', 'sample', 'words.']
Joining result: This-is-a-sample-string-with-sample-words.
Replacing result: This is a sample string with sample words.


In [ ]:
3. Count the no of Words in a String and find longest word in it.

In [12]:
s = input("Enter a sentence: ")
words = s.split()
print("Number of words:", len(words))

longest = max(words, key=len)
print("Longest word:", longest)

Enter a sentence: python programming
Number of words: 2
Longest word: programming


In [21]:
s = input("Enter a string: ").lower()
vowels = "aeiou"
v_count = 0
c_count = 0

for ch in s:
    if ch.isalpha():
        if ch in vowels:
            v_count += 1
        else:
            c_count += 1

print("Vowels:", v_count)
print("Consonants:", c_count)

Enter a string: Python is interesting and easy to learn
Vowels: 12
Consonants: 21


### b) Theory for Lists:

In [ ]:
A list is a collection data type that can store multiple items in 
a single variable.

Properties of Lists:

1) Ordered collection.
2) Mutable (items can be changed after creation).
3) Allows duplicates.
4) Lists are defined inside square brackets [ ].
5) Heterogeneous: It can store different data types together 
   (e.g., integers, strings, floats, even other lists).
6) Indexable and iterable.
7) Dynamic in Size
8) Works with membership operators

### Programs on Lists

In [ ]:
5. Create a list of squares using List Comprehension

In [2]:
# without list comprehension
squares = []
for x in range(1,6):
    squares.append(x**2)
print(squares)

[1, 4, 9, 16, 25]


In [ ]:
Syntax1: [expression for item in iterable]

In [23]:
# with list comprehension
squares = [x**2 for x in range(1, 11)]
print(squares)  

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
6. Create a list of squares for even numbers using List Comprehension

In [22]:
# without list comprehension
nums = []
for x in range(1, 11):
    if x % 2 == 0:
        nums.append(x**2)
print(nums)

[4, 16, 36, 64, 100]


In [ ]:
Syntax2: [expression for item in iterable if condition]

In [24]:
# with list comprehension
nums = [x**2 for x in range(1, 11) if x % 2 == 0]
print(nums)

[4, 16, 36, 64, 100]


In [ ]:
7. Program to find the Second Largest and Second Smallest Numbers
from a list

In [3]:
numbers = [12, 45, 67, 23, 89, 34]
numbers.sort()
print("Second largest number:", numbers[-2])
print("Second smallest number:", numbers[1])

Second largest number: 67
Second smallest number: 23


### c) Theory for Tuples:

In [ ]:
Properties of Tuples-

1. Tuples are Ordered.
2. Immutable → once created, elements cannot be changed.
3. Allows duplicates.
4. Heterogeneous: Can store different data types 
    (int, string, float, etc.).
5. Indexable and iterable.
6. Tuples are defined inside Parenthesis ()
7. Works with membership operators

### Programs on Tuples

In [ ]:
8. Program to demonstrate the In-built methods of Tuples

In [19]:
my_tuple = (10, 20, 30, 20, 40, 20)

print(my_tuple.count(20))   
print(my_tuple.index(20)) 
print(len(my_tuple))
print(max(my_tuple))
print(min(my_tuple))
print(sorted(my_tuple))

3
1
6
40
10
[10, 20, 20, 20, 30, 40]


In [ ]:
9. Program to modify the elements of a tuple

In [6]:
x = ("apple", "banana", "cherry")
y = list(x)  # Convert to list
y.append("orange")  # Add element

y[1] = "kiwi"  #Modify element
x = tuple(y)   # Convert to tuple
print(x)

('apple', 'kiwi', 'cherry', 'orange')


### Difference between lists and arrays

In [10]:
# Adding two lists 
x = [3,4]
y = [5,2]
z = x + y
print(z)  # both the lists get concatenated

[3, 4, 5, 2]


In [16]:
# Addition and muliplication of two list of elements using for loop
x = [3,4]
y = [5,2]

a = [x[i] + y[i] for i in range(len(x))]
print("The sum of two lists is", a)
b = [x[i] * y[i] for i in range(len(x))]
print("The product of two lists is", b)

The sum of two lists is [8, 6]
The product of two lists is [15, 8]


In [15]:
# Addition and muliplication of two arrays using numpy library
import numpy as np

x = np.array([3, 4])
y = np.array([5, 2])

a = x + y
b = x * y 
c = np.dot(x,y)
print("The sum of two arrays is", a)
print("The element-wise multiplication of two arrays is", b)
print("The dot product of two arrays is", c)

The sum of two arrays is [8 6]
The element-wise multiplication of two arrays is [15  8]
The dot product of two arrays is 23


In [ ]:
10. Program to perform addition and multiplication of two square matrices

In [4]:
import numpy as np

x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
y = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

a = x + y
b = x * y
c = np.dot(x, y)
print("Sum of matrices:")
print(a)
print("Element-wise multiplication of two matrices:")
print(b)
print("Dot Product of two matrices:")
print(c)

Sum of matrices:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Element-wise multiplication of two matrices:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Dot Product of two matrices:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
