### Seqeunce Types - Stings, Lists and Tuples

### a) Strings

In [ ]:
1. Add a comma between the characters. If the given word is 
'Apple', it should become 'A,p,p,l,e'

In [1]:
word = "Apple"
result = ""
for i, char in enumerate(word):
    result += char
    if i < len(word) - 1:
        result += ","
print(result)


A,p,p,l,e


In [2]:
word = "Apple"
result = ",".join(word)
print(result)

A,p,p,l,e


In [ ]:
2. Program to replace 
a) the given word with null in a string
b) spaces in the string with -

In [3]:
s = "This is a sample string with sample words."
rem = "sample"
result = s.replace(rem, "")  
print(result)

new_text = s.replace(" ", "-") 
print(new_text)   # replaces all spaces with -

This is a  string with  words.
This-is-a-sample-string-with-sample-words.


In [ ]:
3. Find the Longest Word in a Sentence

In [1]:
s = input("Enter a sentence: ")
words = s.split()
longest = max(words)
print("Longest word:", longest)

Enter a sentence: Python programming
Longest word: programming


In [21]:
s = input("Enter a string: ").lower()
vowels = "aeiou"
v_count = 0
c_count = 0

for ch in s:
    if ch.isalpha():
        if ch in vowels:
            v_count += 1
        else:
            c_count += 1

print("Vowels:", v_count)
print("Consonants:", c_count)

Enter a string: Python is interesting and easy to learn
Vowels: 12
Consonants: 21


### b) Lists

In [ ]:
5. Create a list of squares using List Comprehension

In [2]:
# without list comprehension
squares = []
for x in range(1,6):
    squares.append(x**2)
print(squares)

[1, 4, 9, 16, 25]


In [ ]:
Syntax1: [expression for item in iterable]

In [1]:
# with list comprehension
squares = [x**2 for x in range(1, 6)]
print(squares)  

[1, 4, 9, 16, 25]


In [ ]:
6. Create a list of numbers divisible by both 2 and 3 using List 
Comprehension

In [5]:
# without list comprehension
nums = []
for x in range(1, 21):
    if x % 2 == 0 and x % 3 == 0:
        nums.append(x)
print(nums)

[6, 12, 18]


In [ ]:
Syntax2: [expression for item in iterable if condition]

In [9]:
# with list comprehension
nums = [x for x in range(1, 21) if x % 2 == 0 and x % 3 == 0]
print(nums)

[6, 12, 18]


In [ ]:
7. Extract vowels from a string using List Comprehension

In [1]:
sentence = "List Comprehension Example"
vowels = [ch for ch in sentence if ch.lower() in "aeiou"]
print(vowels) 

['i', 'o', 'e', 'e', 'i', 'o', 'E', 'a', 'e']


In [ ]:
8. Reverse Each Word in a Sentence using List Comprehension

In [2]:
s = input("Enter a sentence: ")
words = s.split()
rw = [i[::-1] for i in words]
print(" ".join(rw))

Enter a sentence: This is PP lab
sihT si PP bal


In [ ]:
9. Program to Find the Second Largest and Second Smallest Numbers
from a list

In [3]:
numbers = [12, 45, 67, 23, 89, 34]
numbers.sort()
print("Second largest number:", numbers[-2])
print("Second smallest number:", numbers[1])

Second largest number: 67
Second smallest number: 23


### c) Tuples

In [ ]:
10. Change the elements of a tuple: 

In [6]:
x = ("apple", "banana", "cherry")
y = list(x)
y.append("orange")

y[1] = "kiwi"
x = tuple(y)
print(x)

('apple', 'kiwi', 'cherry', 'orange')


In [ ]:
11. Program to count an element and find its index from a Tuple

In [4]:
my_tuple = (10, 20, 30, 20, 40, 20)

print(my_tuple.count(20))   
print(my_tuple.index(20)) 

3
1


In [ ]:
To find all the indices

In [16]:
my_tuple = (10, 20, 30, 20, 40, 20)
indices = []
for i, j in enumerate(my_tuple):
    if j == 20:
        indices.append(i)

print(indices)

[1, 3, 5]


In [ ]:
12. Write a python program to perform addition of two square matrices

In [14]:
m1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
m2 = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]

# Perform addition
result = []
for i in range(len(m1)):
    row = []
    for j in range(len(m1[0])):
        row.append(m1[i][j] + m2[i][j])
    result.append(row)
# Print the result
print("Sum of matrices:")
print(result)


Sum of matrices:
[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


In [ ]:
13. Write a python program to perform multiplication of two square 
matrices

In [15]:
m1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
m2 = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]

# Perform multiplication
result = []
for i in range(len(m1)):
    row = []
    for j in range(len(m2[0])):        
        dot_product = sum(m1[i][k] * m2[k][j] for k in range(len(m2)))
        row.append(dot_product)
    result.append(row)

print("Product of two matrices:")
print(result)


Product of two matrices:
[[30, 24, 18], [84, 69, 54], [138, 114, 90]]


### Difference between lists and arrays

In [10]:
# Adding two lists 
x = [3,4]
y = [5,2]
z = x + y
print(z)  # both the lists get concatenated

[3, 4, 5, 2]


In [2]:
# Addition and muliplication of two list of elements using for loop
x = [3,4]
y = [5,2]
print(type(x))

a = [x[i] + y[i] for i in range(len(x))]
print("The sum of two lists is", a)
b = [x[i] * y[i] for i in range(len(x))]
print("The product of two lists is", b)

<class 'list'>
The sum of two lists is [8, 6]
The product of two lists is [15, 8]


In [3]:
# Addition and muliplication of two arrays using numpy library
import numpy as np

x = np.array([3, 4])
y = np.array([5, 2])

print(type(x))

a = x + y
b = x * y 
c = np.dot(x,y)
print("The sum of two arrays is", a)
print("The element-wise multiplication of two arrays is", b)
print("The dot product of two arrays is", c)

<class 'numpy.ndarray'>
The sum of two arrays is [8 6]
The element-wise multiplication of two arrays is [15  8]
The dot product of two arrays is 23


In [ ]:
Program to perform addition and multiplication of two square matrices

In [4]:
import numpy as np

x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
y = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

a = x + y
b = x * y
c = np.dot(x, y)
print("Sum of matrices:")
print(a)
print("Element-wise multiplication of two matrices:")
print(b)
print("Dot Product of two matrices:")
print(c)

Sum of matrices:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Element-wise multiplication of two matrices:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Dot Product of two matrices:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
