In [ ]:
A list is a collection data type that can store multiple items in 
a single variable.

Properties of Lists:

1) Ordered collection.
2) It is mutable (items can be changed after creation).
3) Allows duplicates.
4) Lists are written inside square brackets [ ].
5) Heterogeneous: It can store different data types together 
   (e.g., integers, strings, floats, even other lists).
6) Indexable and iterable.
7) Dynamic in Size

## 1. Creating Lists

In [ ]:
1. Empty List

In [ ]:
my_list = []
print(my_list)   

In [ ]:
2. List with Integers

In [4]:
numbers = [1, 2, 3, 4, 5]
print(numbers)  

[1, 2, 3, 4, 5]


In [ ]:
3. List with Mixed Data Types

In [5]:
mixed = [10, "Python", 3.14, True]
print(mixed) 

[10, 'Python', 3.14, True]


In [ ]:
4. Nested List (List inside a List)

In [4]:
nested = [1, 2, [3, 4], 5]
print(nested)

[1, 2, [3, 4], 5]


In [ ]:
5. Creating List using list() Constructor

In [7]:
word = "Python"
letters = list(word)
print(letters)

['P', 'y', 't', 'h', 'o', 'n']


In [ ]:
6. Creating List with Repeated Elements

In [1]:
x = [1,2,3] * 5
print(x)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


## 2. Properties of Lists

In [ ]:
1. Ordered
Lists maintain the order of elements. The order in which you
insert items is preserved.

In [ ]:
my_list = [10, 20, 30, 40]
print(my_list)       # [10, 20, 30, 40]
print(my_list[0])    # 10 (first element)

In [ ]:
2. Mutable
Lists can be modified after creation (elements can be added, 
removed, or changed).

In [ ]:
my_list = [1, 2, 3]
my_list[1] = 20      # Changing element at index 1
print(my_list)       # [1, 20, 3]

In [ ]:
3. Allow Duplicates
A list can contain duplicate values.

In [ ]:
my_list = [5, 10, 5, 20]
print(my_list)       # [5, 10, 5, 20]

In [ ]:
4. Heterogeneous Elements
A list can store elements of different data types 
(integers, strings, floats, etc.).

In [ ]:
my_list = [10, "Hello", 3.14, True]
print(my_list) 

In [ ]:
5. Indexing and Slicing Supported
You can access elements using indexing (positive/negative)
and retrieve subsets using slicing.

In [ ]:
Explain list slicing with suitable examples. 
Write a program to reverse a list using slicing

In [ ]:
my_list = [10, 20, 30, 40, 50]
print(my_list[2])       # 30 (indexing)
print(my_list[-1])      # 50 (negative index)
print(my_list[1:4])     # [20, 30, 40] (slicing)

In [ ]:
Slicing of a List; Accessing List elements; Negative indexing

In [10]:
my_list = ['p','r','o','g','r','a','m','i','z']

# items from index 2 to index 4
print(my_list[2:5])
# items from index 5 to end
print(my_list[5:])
# items beginning to end
print(my_list[:])
print(my_list[-7:-2])
print(my_list[-2:-7:-1]) # prints in reverse order

['o', 'g', 'r']
['a', 'm', 'i', 'z']
['p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z']
['o', 'g', 'r', 'a', 'm']
['i', 'm', 'a', 'r', 'g']


In [ ]:
Change List items

In [28]:
languages = ['Python', 'Swift', 'C++']

# changing the third item to 'C'
languages[2] = 'C'

print(languages)

['Python', 'Swift', 'C']


In [ ]:
6. Dynamic in Size
Lists can grow or shrink dynamically (no fixed size).

In [ ]:
my_list = [1, 2, 3]
my_list.append(4)    # Adding element
print(my_list)       # [1, 2, 3, 4]
my_list.pop()        # Removing last element
print(my_list) 

## 3. List Methods

In [ ]:
1. append() → Add an item at the end

In [1]:
fruits = ["apple", "banana", "banana"]
fruits.append("cherry")
print(fruits) 

['apple', 'banana', 'banana', 'cherry']


In [ ]:
2. insert() → Add an item at a specific position

In [2]:
fruits.insert(1, "mango")
print(fruits)  

['apple', 'mango', 'banana', 'banana', 'cherry']


In [ ]:
3. extend() → Add multiple items

In [23]:
a = [1, 2]
b = [3, 4]
a.extend(b)
print(a)

[1, 2, 3, 4]


In [ ]:
4. remove() → Remove a specific item

In [3]:
fruits.remove("banana")
print(fruits)   

['apple', 'banana', 'cherry']


In [ ]:
5. pop() → Remove item by index (default: last item)

In [4]:
fruits.pop(1)
print(fruits) 

fruits.pop()
print(fruits)

['apple', 'banana', 'cherry']
['apple', 'banana']


In [ ]:
6. Clear() - Clears the list
   del - Deletes the list

In [5]:
# Clears all the elements
items = [10, 20, 30]
items.clear()
print(items)   # output: Null list

del items
print(items)  #output: Error

[]


NameError: name 'items' is not defined

In [ ]:
7. sort() → Sort list in ascending order

In [21]:
numbers = [5, 2, 9, 1]
numbers.sort()
print(numbers) 

[1, 2, 5, 9]


In [ ]:
8. reverse() → Reverse order of items

In [35]:
numbers = [5, 2, 9, 1]
numbers.sort()
print(numbers)

numbers.reverse()
print(numbers)

[1, 2, 5, 9]
[9, 5, 2, 1]


In [37]:
languages = ['Python', 'Swift', 'C++', 'C', 'Java', 'Rust', 'R']
languages.sort()
print("\nAlphabetical")
print(languages)

print("\nReverse alphabetical")
languages.reverse()
print(languages)


Alphabetical
['C', 'C++', 'Java', 'Python', 'R', 'Rust', 'Swift']

Reverse alphabetical
['Swift', 'Rust', 'R', 'Python', 'Java', 'C++', 'C']


In [ ]:
9. Other Useful Functions

In [9]:
nums = [10, 20, 30, 40, 20]
print(len(nums))     
print(max(nums))     
print(min(nums))     
print(sum(nums))
print(nums.count(20))    # Count occurrences
print(nums.index(20))

5
40
10
120
2
1


In [6]:
# To find all the indices
nums = [10, 20, 30, 40, 20]
indices = []
for i, j in enumerate(nums):
    if j == 20:
        indices.append(i)
        
print(indices)

[1, 4]


In [ ]:
10. Check if an Element exists in a List (Checking Membership)

In [29]:
languages = ['Python', 'Swift', 'C++']

print('C' in languages)    # False
print('Python' in languages) 

False
True


In [ ]:
11. Iterate through the items and print the values using 'for' loop

In [30]:
x = ["apple", "banana", "cherry"]
for i in x:
    print(i)

apple
banana
cherry


In [ ]:
12. Iterate through the items and print the values using for
and range

In [1]:
x = ["apple", "banana", "cherry"]
for i in range(len(x)):
    print(x[i])

apple
banana
cherry


## 4. List Comprehension 

In [ ]:
List comprehension is a concise way to create lists using a
single line of code.

In [ ]:
Syntax: [expression for item in iterable if condition]

### Programs on Lists and List Comprehension

In [ ]:
1. Create a list of squares using List Comprehension

In [ ]:
# without comprehension
squares = []
for x in range(1,6):
    squares.append(x**2)
print(squares)

[1, 4, 9, 16, 25]


In [ ]:
# with comprehension
squares = [x**2 for x in range(1, 6)]
print(squares)  

[1, 4, 9, 16, 25]


In [ ]:
2. Create lists of Even and Odd numbers from 1 to 10 using 
List Comprehension

In [ ]:
#without comprehension
evens = []
odds = []
for x in range(1,11):
    if x % 2 == 0:
        evens.append(x)
    else:
        odds.append(x)
print("The even nos are", evens)  
print("The odd nos are", odds)  

The even nos are [2, 4, 6, 8, 10]
The odd nos are [1, 3, 5, 7, 9]


In [ ]:
# with comprehension
evens = [x for x in range(1, 11) if x % 2 == 0]
print("The even nos are", evens)  
odds = [x for x in range(1, 11) if x % 2 != 0]
print("The odd nos are", odds)  

The even nos are [2, 4, 6, 8, 10]
The odd nos are [1, 3, 5, 7, 9]


In [ ]:
2b) Label "EVEN" or "ODD" for all the numbers in a list
using list comprehension

In [ ]:
[exp_if_true if condition else exp_if_false for item in iterable]

In [ ]:
nums = [1, 2, 3, 4, 5]

labels = ["Even" if x % 2 == 0 else "Odd" for x in nums]
print(labels)

['Odd', 'Even', 'Odd', 'Even', 'Odd']


In [ ]:
3. Convert each word to uppercase using List Comprehension

In [ ]:
x = ["python", "is", "fun"]
upper_words = [i.upper() for i in x]
print(upper_words)

['PYTHON', 'IS', 'FUN']


In [13]:
x = "python is fun"
s = x.split(" ")
print(s)
upper_words = [i.upper() for i in s]
print(upper_words)

['python', 'is', 'fun']
['PYTHON', 'IS', 'FUN']


In [ ]:
4. Convert string characters into uppercase list

In [ ]:
x = "python is fun"
uppercase_chars = [i.upper() for i in x]
print("Uppercase chars:", uppercase_chars)

Uppercase chars: ['P', 'Y', 'T', 'H', 'O', 'N', ' ', 'I', 'S', ' ', 'F', 'U', 'N']


In [ ]:
5. Create a list of numbers divisible by both 2 and 3 
using List Comprehension

In [ ]:
nums = [x for x in range(1, 21) if x % 2 == 0 and x % 3 == 0]
print(nums)

[6, 12, 18]


In [ ]:
6. Extract vowels from a string using List Comprehension

In [ ]:
sentence = "List Comprehension Example"
vowels = [ch for ch in sentence if ch.lower() in "aeiou"]
print(vowels) 

In [ ]:
6b) Label the characters in a string with Vowel or Consonant

In [ ]:
text = "abce123"

result = ["Vowel" if ch.lower() in "aeiou" else "Consonant"
          for ch in text if ch.isalpha()]

print(result)

['Vowel', 'Consonant', 'Consonant', 'Vowel']


In [ ]:
7. Reverse Each Word in a Sentence using List Conprehension

In [ ]:
s = input("Enter a sentence: ")
words = s.split()
reversed_words = [word[::-1] for word in words]
print(" ".join(reversed_words))

Enter a sentence: List comprehension examples
tsiL noisneherpmoc selpmaxe


In [ ]:
8. Multiples of 3 up to 30

In [ ]:
multiples_of_3 = [x for x in range(31) if x % 3 == 0]
print("Multiples of 3:", multiples_of_3)

Multiples of 3: [0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30]


In [ ]:
9. Multiplication table (1 to 3)

In [ ]:
table = [[i*j for j in range(1, 6)] for i in range(1, 4)]
print("Multiplication table:", table)

Multiplication table: [[1, 2, 3, 4, 5], [2, 4, 6, 8, 10], [3, 6, 9, 12, 15]]


## 5. Programs on Lists using functions

In [ ]:
1. Program to Find the Sum of Elements in a List

In [1]:
numbers = [10, 20, 30, 40, 50]
total = sum(numbers)
print("Sum of elements:", total)

Sum of elements: 150


In [ ]:
2. Program to Find the Largest and Smallest Numbers in a List

In [2]:
numbers = [45, 12, 78, 34, 90, 23]
print("Largest number:", max(numbers))
print("Smallest number:", min(numbers))

Largest number: 90
Smallest number: 12


In [ ]:
3. Write a Python program to read 5 numbers into a list 
and then print the largest and smallest numbers.

In [11]:
n = int(input('enter the value of n '))
numbers = []

for i in range(n):
    ele = int(input(f"enter the element {i+1} "))
    numbers.append(ele)
print("Largest number:", max(numbers))
print("Smallest number:", min(numbers))

enter the value of n5
enter the element 16
enter the element 245
enter the element 323
enter the element 465
enter the element 534
Largest number: 65
Smallest number: 6


In [ ]:
4. Program to Count Occurrences of an Element

In [3]:
fruits = ["apple", "banana", "cherry", "apple", "mango", "apple"]
print("Apple occurs:", fruits.count("apple"), "times")

Apple occurs: 3 times


## Differences between Lists and Arrays

In [3]:
# Adding two lists
x = [3,4]
y = [5,2]
z = x + y
print(z)

[3, 4, 5, 2]


In [5]:
# Addition and muliplication of two list of elements using for loop
x = [3,4]
y = [5,2]
print(type(x))

a = [x[i] + y[i] for i in range(len(x))]
print("The sum of two lists is", a)
b = [x[i] * y[i] for i in range(len(x))]
print("The product of two lists is", b)

<class 'list'>
The sum of two lists is [8, 6]
The product of two lists is [15, 8]


In [8]:
# Addition and muliplication of two arrays using numpy library
import numpy as np

x = np.array([3, 4])
y = np.array([5, 2])

print(type(x))

a = x + y
b = x * y 
c = np.dot(x,y)
print("The sum of two arrays is", a)
print("The element-wise multiplication of two arrays is", b)
print("The dot product of two arrays is", c)

<class 'numpy.ndarray'>
The sum of two arrays is [8 6]
The dot product of two arrays is [15  8]
The product of two arrays is 23


In [ ]:
5. Write a python program to perform addition and 
multiplication of two square matrices

In [10]:
import numpy as np

x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
y = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

a = x + y
b = x * y
c = np.dot(x, y)
print("Sum of matrices:")
print(a)
print("Element-wise multiplication of two matrices:")
print(b)
print("Dot Product of two matrices:")
print(c)

Sum of matrices:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Element-wise multiplication of two matrices:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Dot Product of two matrices:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
